version: '3.1'

services:

  db:
    image: 'postgres:latest'
    container_name: 'database_359'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  app:
    container_name: app
    build:
      context: .
    depends_on:
      db :
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "3000:3000"

volumes:
  dbdata: